name: Continue Deployment (Backend)

on:
  push:
    branches:
      - main 
      - master
    paths:
      - 'backend/**'

permissions:
  contents: write
  packages: write

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_NAME }} 

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            PROJECT_DIR="${{ secrets.VPS_PROJECT_DIR }}" 
            cd "$PROJECT_DIR" 
            docker compose down
            docker compose pull
            docker compose up -d
